source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

def pod_for_ads
  
  # 穿山甲
  pod 'Ads-CN', '~> 5.4.1.1'
  
  # 广点通/优量汇
  pod 'GDTMobSDK', '~> 4.14.32'
  
  # 快手
  pod 'KSAdSDK', '~> 3.3.49.1'
  
  # UnityAds
  pod 'UnityAds', '~> 4.8.0'
  
  # Admob/GoogleAd
  pod 'Google-Mobile-Ads-SDK', '~> 10.9.0'
  
  # 百度SDK
  pod 'BaiduMobAdSDK', '~> 5.311'
  
  # SigmobAd
  pod 'SigmobAd-iOS', '~> 4.9.3'
  
  # 游可赢
  pod 'KlevinAdSDK', '~> 2.11.0.215'
  
  # MintegralAdSDK
  pod 'MintegralAdSDK', '~> 7.4.2'
  
end

target 'ABUAdDemo' do
  
  use_frameworks!

  pod 'CSJGroMore', :path => '../'

  pod_for_ads
  
end

target 'ABUAdDemoSwift' do
  
  use_frameworks!

  pod 'CSJGroMore', :path => '../'
  
  pod_for_ads

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
